# Generated by Django 4.1.7 on 2023-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0002_alter_asset_company_alter_assetcoordinate_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='salesforce_password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='salesforce_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
