# Generated by Django 4.1.7 on 2023-06-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0003_company_salesforce_password_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='salesforce_password_hash',
            new_name='salesforce_password',
        ),
    ]
