# Generated by Django 4.1.7 on 2023-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0004_rename_salesforce_password_hash_company_salesforce_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company'),
        ),
    ]
