# Generated by Django 4.1.7 on 2023-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0006_customuser_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcoordinate',
            name='isEveryLink',
            field=models.BooleanField(default=False),
        ),
    ]
