# Generated by Django 4.1.7 on 2023-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0007_assetcoordinate_iseverylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
