# Generated by Django 4.1.7 on 2023-07-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
