# Generated by Django 4.1.7 on 2023-07-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0010_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
    ]
